main:
    random_seed: 'nips2019'
    saved_dir: '/home/tony/Documents//nips2019/models/kits_seg/unet3d/train'

dataset:
    name: 'KitsSegDataset'
    kwargs:
        data_dir: '/home/tony/Documents/kits19_preprocessed/data'
        data_split_csv: '/home/tony/Documents/kits19_preprocessed/dataset_split.csv'
        train_preprocessings:
            - name: 'Normalize'
            - name: 'RandomCrop'
              kwargs:
                  size: [192, 192, 24]
        valid_preprocessings:
            - name: 'Normalize'
            - name: 'PositiveCrop'
              kwargs:
                  positive_sampling_rate: 1.0
                  size: [192, 192, 24]
        augments:
            - name: 'RandomElasticDeformation'
            - name: 'RandomHorizontalFlip'
            - name: 'RandomVerticalFlip'
        transforms:
            - name: 'ToTensor'
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 2
        valid_batch_size: 1
        shuffle: true
        num_workers: 4

net:
    name: 'UNet3D'
    kwargs:
        in_channels: 1
        out_channels: 3
        num_features: [32, 64, 128, 256, 512]
        
losses:
    - name: 'DiceLoss'
      weight: 1.0

metrics:
    - name: 'Dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'KitsSegLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'KitsSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 1000
